# Generated by Django 4.2.4 on 2023-08-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Major",
                "verbose_name_plural": "Majors",
            },
        ),
    ]
