# Generated by Django 4.2.4 on 2023-08-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0002_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="morjor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="MainApp.major",
            ),
        ),
    ]
