# Generated by Django 4.2.4 on 2023-08-03 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0003_student_morjor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="morjor",
            new_name="major",
        ),
    ]
